# Generated by Django 5.1.3 on 2025-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_customuser_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну проживания",
                max_length=20,
                null=True,
                verbose_name="Страна проживания",
            ),
        ),
    ]
