# Generated by Django 5.1.3 on 2024-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
