# Generated by Django 5.1.3 on 2024-12-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья блога",
                "verbose_name_plural": "Статьи блога",
            },
        ),
    ]
